export { supabase } from './client';
export type {
  // Enums
  UserRole,
  GameFormat,
  MatchStatus,
  AuditAction,
  ImportStatus,
  ImportRowStatus,
  DisputeStatus,

  // Row types
  Profile,
  League,
  Division,
  Team,
  Player,
  TeamPlayer,
  SkillLevelHistory,
  TeamMatch,
  Lineup,
  IndividualMatch,
  RacksEightBall,
  RacksNineBall,
  ScorecardSession,
  Import,
  ImportRow,
  AuditLogEntry,
  Dispute,

  // Insert types
  ProfileInsert,
  LeagueInsert,
  DivisionInsert,
  TeamInsert,
  PlayerInsert,
  TeamPlayerInsert,
  SkillLevelHistoryInsert,
  TeamMatchInsert,
  LineupInsert,
  IndividualMatchInsert,
  RacksEightBallInsert,
  RacksNineBallInsert,
  ScorecardSessionInsert,
  ImportInsert,
  ImportRowInsert,
  AuditLogEntryInsert,
  DisputeInsert,

  // Update types
  ProfileUpdate,
  LeagueUpdate,
  DivisionUpdate,
  TeamUpdate,
  PlayerUpdate,
  TeamPlayerUpdate,
  TeamMatchUpdate,
  LineupUpdate,
  IndividualMatchUpdate,
  RacksEightBallUpdate,
  RacksNineBallUpdate,
  ScorecardSessionUpdate,
  ImportUpdate,
  ImportRowUpdate,
  DisputeUpdate,

  // Aggregate database type
  Database,
} from './types';
